import CoreLocation
import MapKit

final class QuestGenerationService {
    private let questService: QuestService
    private let storageService: StorageService

    /// Tracks geohashes we've already attempted generation for this session,
    /// preventing redundant searches on repeated map loads.
    private var attemptedGeoHashes: Set<String> = []

    init(questService: QuestService, storageService: StorageService = StorageService()) {
        self.questService = questService
        self.storageService = storageService
    }

    // MARK: - Public API

    /// Deactivates all existing auto-generated quests in the area then generates a fresh batch.
    /// Resets the geohash cache so generation always proceeds regardless of prior runs.
    func forceRegenerate(near coordinate: CLLocationCoordinate2D) async {
        do {
            try await questService.deactivateAutoGeneratedQuestsInRegion(
                centerLat: coordinate.latitude,
                centerLon: coordinate.longitude
            )
        } catch {
            print("[GeoQuest] Could not deactivate old quests: \(error)")
        }
        attemptedGeoHashes.removeAll()
        await generateQuestsIfNeeded(near: coordinate)
    }

    /// Generates quests near the coordinate if the area is sparse.
    /// Safe to call multiple times — skips if already attempted for this geohash.
    func generateQuestsIfNeeded(near coordinate: CLLocationCoordinate2D) async {
        let geoHash = GeoHash.encode(latitude: coordinate.latitude, longitude: coordinate.longitude)

        guard !attemptedGeoHashes.contains(geoHash) else { return }
        attemptedGeoHashes.insert(geoHash)

        do {
            let existingQuests = try await questService.fetchQuestsInRegion(
                centerLat: coordinate.latitude,
                centerLon: coordinate.longitude
            )

            let activeCount = existingQuests.filter { $0.isActive }.count
            guard activeCount < AppConstants.Generation.maxQuestsPerRegion else { return }

            let slotsAvailable = AppConstants.Generation.maxQuestsPerRegion - activeCount
            let questsToGenerate = min(
                Int.random(in: AppConstants.Generation.batchSizeRange),
                slotsAvailable
            )
            guard questsToGenerate > 0 else { return }

            // Fetch real-world map data — use broader, more varied queries
            let nearbyPlaces = await searchNearbyPlaces(near: coordinate)
            guard nearbyPlaces.count >= 2 else { return }

            let streetInfo = await reverseGeocode(coordinate: coordinate)

            // Shuffle the full pool once; each quest picks a non-overlapping slice
            let shuffledPool = nearbyPlaces.shuffled()

            for i in 0..<questsToGenerate {
                // Rotate through the POI pool so each quest anchors to a different place,
                // spreading quests across the area instead of clustering near one POI.
                let poolSize = shuffledPool.count
                let startIndex = (i * 3) % poolSize
                let placeCount = min(poolSize - startIndex, Int.random(in: 2...4))
                guard placeCount >= 2 else { continue }
                let questPlaces = Array(shuffledPool[startIndex..<(startIndex + placeCount)])

                // Place quest near the first POI with a healthy offset for variety.
                // Use a wider range than before so quests in a batch aren't on top of each other.
                let questCoord = randomOffset(
                    from: self.coordinate(of: questPlaces[0]),
                    metersRange: 40...250
                )

                var quest = buildQuest(
                    near: questCoord,
                    places: questPlaces,
                    streetInfo: streetInfo
                )

                let questId = try await questService.createQuest(quest)

                // Capture and upload a MapKit snapshot for this quest's area.
                // Try up to 3 times — map tiles may not be cached on first attempt.
                for attempt in 1...3 {
                    if let snapshotData = await captureMapSnapshot(
                        coordinate: questCoord,
                        spanMeters: 400
                    ) {
                        let path = "quests/\(questId)/cover.jpeg"
                        if let url = try? await storageService.uploadImage(data: snapshotData, path: path) {
                            try? await questService.updateImageURL(questId: questId, imageURL: url.absoluteString)
                            break
                        }
                    }
                    if attempt < 3 {
                        try? await Task.sleep(for: .seconds(Double(attempt) * 1.5))
                    }
                }
            }
        } catch {
            // Quest generation is non-critical — never block the player experience
            print("[GeoQuest] Quest generation failed: \(error)")
        }
    }

    // MARK: - Map Data Fetching

    private func searchNearbyPlaces(near coordinate: CLLocationCoordinate2D) async -> [MKMapItem] {
        // Rotate through multiple query types for variety; collect up to 30 results total.
        let queryGroups = [
            ["restaurant", "cafe", "coffee"],
            ["park", "library", "museum"],
            ["store", "shop", "pharmacy"],
            ["hotel", "gym", "theater"],
        ].shuffled()

        var collected: [MKMapItem] = []
        var seenNames = Set<String>()

        for queries in queryGroups {
            let query = queries.randomElement()!
            let request = MKLocalSearch.Request()
            request.naturalLanguageQuery = query
            request.region = MKCoordinateRegion(
                center: coordinate,
                latitudinalMeters: AppConstants.Generation.poiSearchRadiusMeters * 2,
                longitudinalMeters: AppConstants.Generation.poiSearchRadiusMeters * 2
            )
            request.resultTypes = .pointOfInterest

            do {
                let search = MKLocalSearch(request: request)
                let response = try await search.start()
                for item in response.mapItems {
                    guard let name = item.name, !seenNames.contains(name) else { continue }
                    seenNames.insert(name)
                    collected.append(item)
                }
                if collected.count >= 30 { break }
            } catch {
                continue
            }
        }
        return collected
    }

    private struct StreetInfo {
        let streetName: String?
        let neighborhood: String?
        let city: String?
        let subThoroughfare: String?
    }

    private func reverseGeocode(coordinate: CLLocationCoordinate2D) async -> StreetInfo {
        let location = CLLocation(latitude: coordinate.latitude, longitude: coordinate.longitude)
        let empty = StreetInfo(streetName: nil, neighborhood: nil, city: nil, subThoroughfare: nil)

        if #available(iOS 26, *) {
            guard let request = MKReverseGeocodingRequest(location: location) else { return empty }
            do {
                let mapItems = try await request.mapItems
                guard let item = mapItems.first else { return empty }
                let city = item.address?.shortAddress
                return StreetInfo(streetName: nil, neighborhood: city, city: city, subThoroughfare: nil)
            } catch {
                return empty
            }
        } else {
            do {
                let geocoder = CLGeocoder()
                let placemarks = try await geocoder.reverseGeocodeLocation(location)
                guard let pm = placemarks.first else { return empty }
                return StreetInfo(
                    streetName: pm.thoroughfare,
                    neighborhood: pm.subLocality ?? pm.locality,
                    city: pm.locality,
                    subThoroughfare: pm.subThoroughfare
                )
            } catch {
                return empty
            }
        }
    }

    // MARK: - MKMapItem Compatibility
    // MKMapItem.placemark is deprecated in iOS 26. These helpers use the new
    // API when available and fall back to placemark on older versions.

    private func coordinate(of item: MKMapItem) -> CLLocationCoordinate2D {
        if #available(iOS 26, *) {
            return item.location.coordinate
        }
        return item.placemark.coordinate
    }

    private func streetName(of item: MKMapItem, fallback: String?) -> String {
        if #available(iOS 26, *) {
            return fallback ?? "the street"
        }
        return item.placemark.thoroughfare ?? fallback ?? "the street"
    }

    private func addressNumber(of item: MKMapItem) -> String? {
        if #available(iOS 26, *) {
            return nil
        }
        return item.placemark.subThoroughfare
    }

    // MARK: - Quest Building

    private func buildQuest(
        near coordinate: CLLocationCoordinate2D,
        places: [MKMapItem],
        streetInfo: StreetInfo
    ) -> Quest {
        let primaryPlace = places[0]
        let primaryName = primaryPlace.name ?? "the landmark"
        let rawStreet = streetName(of: primaryPlace, fallback: streetInfo.streetName)
        // Guard against a full address string leaking into the street slot.
        // A street name should be short — if it looks like a full address (contains digits),
        // fall back to the neighborhood or a generic placeholder.
        let streetForTemplate = sanitizeStreetName(rawStreet, area: streetInfo.neighborhood ?? streetInfo.city)
        let area = streetInfo.neighborhood ?? streetInfo.city ?? "the area"

        let title = fillTemplate(
            QuestGenerationData.questTitleTemplates.randomElement()!,
            place: primaryName, street: streetForTemplate, area: area
        )

        let description = fillTemplate(
            QuestGenerationData.questDescriptionTemplates.randomElement()!,
            place: primaryName, street: streetForTemplate, area: area
        )

        let steps = generateSteps(places: places, streetInfo: streetInfo, sanitizedStreet: streetForTemplate)
        let secretCode = generateSecretCode(from: places, streetInfo: streetInfo)
        let difficulty = weightedRandomDifficulty()

        // Spread creation dates across the past few weeks for a natural feel
        let daysAgo = Int.random(in: 1...30)
        let hoursAgo = Int.random(in: 0...23)
        var createdDate = Calendar.current.date(byAdding: .day, value: -daysAgo, to: Date()) ?? Date()
        createdDate = Calendar.current.date(byAdding: .hour, value: -hoursAgo, to: createdDate) ?? createdDate

        var quest = Quest(
            creatorId: AppConstants.Generation.creatorIdPrefix + UUID().uuidString,
            creatorDisplayName: QuestGenerationData.fakeUsernames.randomElement()!,
            title: String(title.prefix(AppConstants.maxQuestTitleCharacters)),
            description: String(description.prefix(AppConstants.maxQuestDescriptionCharacters)),
            latitude: coordinate.latitude,
            longitude: coordinate.longitude,
            steps: steps,
            secretCode: secretCode,
            iconName: QuestGenerationData.questIcons.randomElement()!,
            iconColor: QuestGenerationData.questColors.randomElement()!,
            difficulty: difficulty
        )
        quest.createdAt = createdDate

        return quest
    }

    /// Strips full addresses from the street slot.
    /// If the string contains a leading digit sequence (e.g. "123 Main St") it looks like
    /// a full address; return the area name instead so quest text stays clean.
    private func sanitizeStreetName(_ raw: String, area: String?) -> String {
        let trimmed = raw.trimmingCharacters(in: .whitespaces)
        // Contains leading digit → looks like "123 Main St"
        if trimmed.first?.isNumber == true {
            return area ?? "the area"
        }
        // Unusually long (> 40 chars) — probably a full address or description
        if trimmed.count > 40 {
            return area ?? "the area"
        }
        return trimmed.isEmpty ? (area ?? "the area") : trimmed
    }

    // MARK: - Step Generation

    private func generateSteps(
        places: [MKMapItem],
        streetInfo: StreetInfo,
        sanitizedStreet: String
    ) -> [QuestStep] {
        var steps: [QuestStep] = []
        let area = streetInfo.neighborhood ?? streetInfo.city ?? "the area"
        var orderIndex = 0

        // First step — orient the player
        if let first = places.first {
            let name = first.name ?? "the landmark"
            let street = sanitizedStreet
            let instruction = fillTemplate(
                QuestGenerationData.firstStepTemplates.randomElement()!,
                place: name, street: street, area: area
            )
            steps.append(QuestStep(orderIndex: orderIndex, instruction: instruction))
            orderIndex += 1
        }

        // Middle steps — navigate between POIs
        if places.count > 2 {
            for i in 1..<(places.count - 1) {
                let place = places[i]
                let name = place.name ?? "the next spot"
                let street = sanitizeStreetName(
                    streetName(of: place, fallback: streetInfo.streetName),
                    area: streetInfo.neighborhood ?? streetInfo.city
                )
                let direction = QuestGenerationData.directions.randomElement()!
                let side = QuestGenerationData.sides.randomElement()!

                let template = QuestGenerationData.middleStepTemplates.randomElement()!
                var instruction = fillTemplate(template, place: name, street: street, area: area)
                instruction = instruction
                    .replacingOccurrences(of: "{direction}", with: direction)
                    .replacingOccurrences(of: "{side}", with: side)
                steps.append(QuestStep(orderIndex: orderIndex, instruction: instruction))
                orderIndex += 1
            }
        }

        // Optional observation step for 2-place quests to add depth
        if places.count == 2, Bool.random() {
            let street = sanitizedStreet
            let instruction = fillTemplate(
                QuestGenerationData.observationStepTemplates.randomElement()!,
                place: "", street: street, area: area
            )
            steps.append(QuestStep(orderIndex: orderIndex, instruction: instruction))
            orderIndex += 1
        }

        // Final step — find the code
        if let last = places.last, places.count > 1 {
            let name = last.name ?? "your destination"
            let street = sanitizeStreetName(
                streetName(of: last, fallback: streetInfo.streetName),
                area: streetInfo.neighborhood ?? streetInfo.city
            )
            let addrNum = addressNumber(of: last)

            let instruction: String
            if addrNum != nil {
                instruction = fillTemplate(
                    QuestGenerationData.finalStepTemplates.randomElement()!,
                    place: name, street: street, area: area
                )
            } else if let placeName = last.name, extractNameCode(from: placeName) != nil {
                let codeLength = min(6, placeName.filter { $0.isLetter }.count)
                var tmpl = QuestGenerationData.nameBasedFinalStepTemplates.randomElement()!
                tmpl = tmpl.replacingOccurrences(of: "{n}", with: "\(codeLength)")
                instruction = fillTemplate(tmpl, place: name, street: street, area: area)
            } else {
                instruction = fillTemplate(
                    QuestGenerationData.finalStepTemplates.randomElement()!,
                    place: name, street: street, area: area
                )
            }
            steps.append(QuestStep(orderIndex: orderIndex, instruction: instruction))
        }

        return steps
    }

    // MARK: - Secret Code Generation

    private func generateSecretCode(from places: [MKMapItem], streetInfo: StreetInfo) -> String {
        // Collect all candidate strategies and pick one randomly for variety.
        var candidates: [String] = []

        // Strategy 1: Address number from the final place
        if let last = places.last,
           let address = addressNumber(of: last),
           address.count >= AppConstants.minSecretCodeLength {
            candidates.append(String(address.prefix(AppConstants.maxSecretCodeLength)))
        }

        // Strategy 2: First letters of the last place's name (up to 6)
        if let last = places.last, let code = extractNameCode(from: last.name ?? "") {
            candidates.append(code)
        }

        // Strategy 3: Initials from all places (e.g. SBCP for 4 POIs)
        let initials = places
            .compactMap { $0.name?.first }
            .map { String($0).uppercased() }
            .joined()
        if initials.count >= AppConstants.minSecretCodeLength {
            candidates.append(String(initials.prefix(AppConstants.maxSecretCodeLength)))
        }

        // Strategy 4: Word-shaped code — vowel-consonant pattern, easy to type
        candidates.append(randomPronounceable(length: Int.random(in: 5...6)))

        // Strategy 5: Mixed alphanumeric using place name + a digit
        if let first = places.first, let name = first.name {
            let letters = name.uppercased().filter { $0.isLetter }
            let prefix = String(letters.prefix(3))
            let suffix = String(Int.random(in: 10...99))
            let mixed = prefix + suffix
            if mixed.count >= AppConstants.minSecretCodeLength {
                candidates.append(mixed)
            }
        }

        // Strategy 6: Area-based code (first 4 letters of neighborhood + digit)
        if let area = streetInfo.neighborhood ?? streetInfo.city {
            let letters = area.uppercased().filter { $0.isLetter }
            let areaPrefix = String(letters.prefix(4))
            let digit = String(Int.random(in: 2...9))
            let code = areaPrefix + digit
            if code.count >= AppConstants.minSecretCodeLength {
                candidates.append(code)
            }
        }

        // Pick one candidate at random for maximum variety
        if let chosen = candidates.randomElement() {
            return String(chosen.prefix(AppConstants.maxSecretCodeLength))
        }

        return randomCode(length: 6)
    }

    private func extractNameCode(from name: String) -> String? {
        let letters = name.uppercased().filter { $0.isLetter }
        guard letters.count >= AppConstants.minSecretCodeLength else { return nil }
        return String(letters.prefix(6))
    }

    private func randomCode(length: Int) -> String {
        let chars = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"
        return String((0..<length).map { _ in chars.randomElement()! })
    }

    /// Generates a pronounceable code using alternating consonant-vowel pairs.
    private func randomPronounceable(length: Int) -> String {
        let consonants = Array("BCDFGHJKLMNPQRSTVWXYZ")
        let vowels = Array("AEIOU")
        var result = ""
        for i in 0..<length {
            result += i % 2 == 0
                ? String(consonants.randomElement()!)
                : String(vowels.randomElement()!)
        }
        return result
    }

    // MARK: - Map Snapshot

    /// Captures a map snapshot centred on `coordinate`.
    /// Tries standard map first (most reliable for tile availability),
    /// then falls back to hybrid/satellite imagery.
    /// Returns JPEG data or nil if snapshotting fails entirely.
    @MainActor
    private func captureMapSnapshot(
        coordinate: CLLocationCoordinate2D,
        spanMeters: Double
    ) async -> Data? {
        // Standard first — tiles are most reliably cached / available.
        let mapTypes: [MKMapType] = [.standard, .hybrid, .satellite]

        for mapType in mapTypes {
            let options = MKMapSnapshotter.Options()
            options.region = MKCoordinateRegion(
                center: coordinate,
                latitudinalMeters: spanMeters,
                longitudinalMeters: spanMeters
            )
            options.size = CGSize(width: 800, height: 480)
            options.mapType = mapType
            options.showsBuildings = true
            options.traitCollection = UITraitCollection(displayScale: 2.0)

            let snapshotter = MKMapSnapshotter(options: options)
            do {
                let snapshot = try await snapshotter.start()
                let image = drawPin(on: snapshot)
                if let data = image.jpegData(compressionQuality: 0.82),
                   data.count > 5_000 {
                    // Guard against blank/empty snapshots (typically < 5 KB)
                    return data
                }
            } catch {
                continue
            }
        }
        return nil
    }

    /// Draws a small location pin at the center of the snapshot image.
    @MainActor
    private func drawPin(on snapshot: MKMapSnapshotter.Snapshot) -> UIImage {
        let image = snapshot.image
        let renderer = UIGraphicsImageRenderer(size: image.size)
        return renderer.image { ctx in
            image.draw(at: .zero)

            // Draw a small pin at center
            let center = CGPoint(x: image.size.width / 2, y: image.size.height / 2)
            let pinSize: CGFloat = 24
            let pinRect = CGRect(
                x: center.x - pinSize / 2,
                y: center.y - pinSize,
                width: pinSize,
                height: pinSize
            )

            // Pin shadow
            ctx.cgContext.setFillColor(UIColor.black.withAlphaComponent(0.3).cgColor)
            ctx.cgContext.fillEllipse(in: CGRect(
                x: center.x - 8, y: center.y - 2, width: 16, height: 6
            ))

            // Pin body
            ctx.cgContext.setFillColor(UIColor(red: 1, green: 0.42, blue: 0.2, alpha: 1).cgColor)
            ctx.cgContext.fillEllipse(in: pinRect.insetBy(dx: 2, dy: 2))

            // Pin dot
            ctx.cgContext.setFillColor(UIColor.white.cgColor)
            ctx.cgContext.fillEllipse(in: CGRect(
                x: center.x - 4, y: center.y - pinSize + 6, width: 8, height: 8
            ))
        }
    }

    // MARK: - Difficulty Weighting

    private func weightedRandomDifficulty() -> QuestDifficulty {
        let roll = Int.random(in: 1...100)
        switch roll {
        case 1...35: return .easy
        case 36...65: return .medium
        case 66...85: return .hard
        default: return .expert
        }
    }

    // MARK: - Geo Utilities

    private func randomOffset(
        from coordinate: CLLocationCoordinate2D,
        metersRange: ClosedRange<Double>
    ) -> CLLocationCoordinate2D {
        let distance = Double.random(in: metersRange)
        let bearing = Double.random(in: 0..<360) * .pi / 180

        let lat1 = coordinate.latitude * .pi / 180
        let lon1 = coordinate.longitude * .pi / 180
        let earthRadius = 6_371_000.0

        let angDist = distance / earthRadius

        let lat2 = asin(
            sin(lat1) * cos(angDist) + cos(lat1) * sin(angDist) * cos(bearing)
        )
        let lon2 = lon1 + atan2(
            sin(bearing) * sin(angDist) * cos(lat1),
            cos(angDist) - sin(lat1) * sin(lat2)
        )

        return CLLocationCoordinate2D(
            latitude: lat2 * 180 / .pi,
            longitude: lon2 * 180 / .pi
        )
    }

    // MARK: - Template Helpers

    private func fillTemplate(_ template: String, place: String, street: String, area: String) -> String {
        template
            .replacingOccurrences(of: "{place}", with: place)
            .replacingOccurrences(of: "{street}", with: street)
            .replacingOccurrences(of: "{area}", with: area)
    }
}
